import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Manual',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'manual'}],
    },
    {
      type: 'category',
      label: 'Tutorial',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'tutorial'}],
    },
  ],
};

export default sidebars;
